# Generated by Django 2.1.4 on 2019-01-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc', models.CharField(max_length=1000)),
                ('bank_id', models.CharField(max_length=1000)),
                ('branch', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('district', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=1000)),
                ('bank_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
